config/routes.rb
Monologue::Engine.routes.draw do
  root to:  "posts#index"
  get "/page/:page", to:  "posts#index", as:  "posts_page"
  get "/feed" => "posts#feed", as:  "feed", defaults: {format: :rss}

  get "/tags/:tag" =>"tags#show", as: "tags_page"

  namespace :admin, path: "monologue" do
    get "/" => "posts#index", as:  "" # responds to admin_url and admin_path
    get "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    resources :sessions
    resources :posts
    resources :users
    get "comments" => "comments#show", as: "comments"

    match "/post/preview"=>"posts#preview", :as=>"post_preview", :via => [:put, :post]
  end

  get "*post_url" => "posts#show", as:  "post"
end

app/models/monologue/post.rb
class Monologue::Post < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  before_validation :generate_url
  belongs_to :user

  scope :default,  -> {order("published_at DESC, monologue_posts.created_at DESC, monologue_posts.updated_at DESC") }
  scope :published, -> { default.where(published: true).where("published_at <= ?", DateTime.now) }

  default_scope{includes(:tags)}

  validates :user_id, presence: true
  validates :title, :content, :url, :published_at, presence: true
  validates :url, uniqueness: true
  validate :url_do_not_start_with_slash

  def author
    user.name
  end

  def tag_list= tags_attr
    self.tag!(tags_attr.split(","))
  end

  def tag_list
    self.tags.map { |tag| tag.name }.join(", ") if self.tags
  end

  def tag!(tags_attr)
    self.tags = tags_attr.map(&:strip).reject(&:blank?).map do |tag|
      Monologue::Tag.where(name: tag).first_or_create
    end
  end

  def full_url
    "#{Monologue::Engine.routes.url_helpers.root_path}#{self.url}"
  end

  def published_in_future?
    self.published && self.published_at > DateTime.now
  end

  def self.page p
    per_page = Monologue::Config.posts_per_page || 10
    set_total_pages(per_page)
    p = (p.nil? ? 0 : p.to_i - 1)
    offset =  p * per_page
    self.limit(per_page).offset(offset)
  end

  def self.total_pages
    @number_of_pages
  end

  def self.set_total_pages per_page
    @number_of_pages = self.count / per_page + (self.count % per_page == 0 ? 0 : 1)
  end

  private

  def generate_url
    return unless self.url.blank?
    year = self.published_at.class == ActiveSupport::TimeWithZone ? self.published_at.year : DateTime.now.year
    self.url = "#{year}/#{self.title.parameterize}"
  end

  def url_do_not_start_with_slash
    errors.add(:url, I18n.t("activerecord.errors.models.monologue/post.attributes.url.start_with_slash")) if self.url.start_with?("/")
  end

end

app/models/monologue/tag.rb
class Monologue::Tag < ActiveRecord::Base
  validates :name, uniqueness: true,presence: true
  has_many :taggings
  has_many :posts,through: :taggings

  def posts_with_tag
    self.posts.published
  end

  def frequency
    posts_with_tag.size
  end
end

app/models/monologue/tagging.rb
class Monologue::Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/monologue/user.rb
class Monologue::User < ActiveRecord::Base
  has_many :posts

  has_secure_password

  validates_presence_of :password, on: :create
  validates_presence_of :name
  validates :email , presence: true, uniqueness: true


  def can_delete?(user)
    return false if self==user
    return false if user.posts.any?
    true
  end
end

app/controllers/monologue/admin/base_controller.rb
class Monologue::Admin::BaseController < Monologue::ApplicationController
  include Monologue::ControllerHelpers::Auth
  force_ssl if Monologue::Config.admin_force_ssl # TODO: find a way to test that with capybara
  
  layout "layouts/monologue/admin"
end

app/controllers/monologue/admin/comments_controller.rb
class Monologue::Admin::CommentsController < Monologue::Admin::BaseController
  def show
  end
end

app/controllers/monologue/admin/posts_controller.rb
class Monologue::Admin::PostsController < Monologue::Admin::BaseController
  respond_to :html
  before_filter :load_post, only: [:edit, :update]
  
  def index
    @posts = Monologue::Post.default
  end

  def new
    @post = Monologue::Post.new
  end

  ## Preview a post without saving.
  def preview
    # mockup our models for preview.
    @post = Monologue::Post.new post_params
    @post.user_id = monologue_current_user.id
    @post.published_at = Time.zone.now
    # render it exactly as it would display when live.
    render "/monologue/posts/show", layout: Monologue::Config.layout || "/layouts/monologue/application"
  end

  def create
    @post = Monologue::Post.new post_params
    @post.user_id = monologue_current_user.id
    if @post.save
      prepare_flash_and_redirect_to_edit()
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      prepare_flash_and_redirect_to_edit()
    else
      render :edit
    end
  end

  def destroy
    post = Monologue::Post.find(params[:id])
    if post.destroy
      redirect_to admin_posts_path, notice:  I18n.t("monologue.admin.posts.delete.removed")
    else
      redirect_to admin_posts_path, alert: I18n.t("monologue.admin.posts.delete.failed")
    end
  end

private
  def load_post
    @post = Monologue::Post.find(params[:id])
  end

  def prepare_flash_and_redirect_to_edit
    if @post.published_in_future? && ActionController::Base.perform_caching
      flash[:warning] = I18n.t("monologue.admin.posts.#{params[:action]}.saved_with_future_date_and_cache")
    else
      flash[:notice] =  I18n.t("monologue.admin.posts.#{params[:action]}.saved")
    end
    redirect_to edit_admin_post_path(@post)
  end

  def post_params
    params.require(:post).permit(:published, :tag_list,:title,:content,:url,:published_at)
  end
end

app/controllers/monologue/admin/sessions_controller.rb
class Monologue::Admin::SessionsController < Monologue::Admin::BaseController
  skip_before_filter :authenticate_user!
  
  def new
  end

  def create
    user = Monologue::User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:monologue_user_id] = user.id
      redirect_to admin_url, notice: t("monologue.admin.sessions.messages.logged_in")
    else
      flash.now.alert = t("monologue.admin.sessions.messages.invalid")
      render "new"
    end
  end

  def destroy
    session[:monologue_user_id] = nil
    redirect_to admin_url, notice: t("monologue.admin.sessions.messages.logged_out")
  end
end

app/controllers/monologue/admin/users_controller.rb
class Monologue::Admin::UsersController < Monologue::Admin::BaseController

  before_filter :load_user, except: [:index, :new, :create]

  def edit

  end

  def new
    @user = Monologue::User.new
  end

  def update
    if @user.update user_params
      flash.notice = "User modified"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice:  I18n.t("monologue.admin.users.delete.removed", user: @user.name)
    else
      redirect_to admin_users_path, alert: I18n.t("monologue.admin.users.delete.failed", user: @user.name)
   end
  end

  def create
    @user = Monologue::User.new user_params
    if @user.save
      flash.notice = I18n.t("monologue.admin.users.create.success")
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def index
    @users = Monologue::User.all
  end

  private
    def load_user
      @user = Monologue::User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/monologue/application_controller.rb
class Monologue::ApplicationController < ApplicationController
  include Monologue::ControllerHelpers::User

  layout Monologue::Config.layout if Monologue::Config.layout # TODO: find a way to test that. It was asked in issue #54 (https://github.com/jipiboily/monologue/issues/54)

  before_filter :recent_posts, :all_tags

  def recent_posts
    @recent_posts = Monologue::Post.published.limit(3)
  end

  def all_tags
    @tags = Monologue::Tag.order("name").select{|t| t.frequency>0}
    #could use minmax here but it's only supported with ruby > 1.9'
    @tags_frequency_min = @tags.map{|t| t.frequency}.min
    @tags_frequency_max = @tags.map{|t| t.frequency}.max
  end

  def not_found
    # fallback to the default 404.html page from main_app.
    file = Rails.root.join('public', '404.html')
    if file.exist?
      render file: file.cleanpath.to_s.gsub(%r{#{file.extname}$}, ''),
         layout: false, status: 404, formats: [:html]
    else
      render action: "404", status: 404, formats: [:html]
    end
  end

end

app/controllers/monologue/controller_helpers/auth.rb
require 'active_support/concern'

module Monologue
  module ControllerHelpers
    module Auth
      extend ActiveSupport::Concern
      include Monologue::ControllerHelpers::User

      included do
        before_filter :authenticate_user!
      end

      private
      def authenticate_user!
         if monologue_current_user.nil?
           redirect_to monologue.admin_login_url, alert: I18n.t("monologue.admin.login.need_auth")
         end
      end
    end
  end
end

app/controllers/monologue/controller_helpers/user.rb
require 'active_support/concern'

module Monologue
  module ControllerHelpers
    module User
      extend ActiveSupport::Concern

      included do
        helper_method :monologue_current_user
      end

      private
      def monologue_current_user
        @monologue_current_user ||= Monologue::User.find(session[:monologue_user_id]) if session[:monologue_user_id]
      end
    end
  end
end

app/controllers/monologue/posts_controller.rb
class Monologue::PostsController < Monologue::ApplicationController
  def index
    @page = params[:page].nil? ? 1 : params[:page]
    @posts = Monologue::Post.published.page(@page)
  end

  def show
    if monologue_current_user
      @post = Monologue::Post.default.where("url = :url", {url: params[:post_url]}).first
    else
      @post = Monologue::Post.published.where("url = :url", {url: params[:post_url]}).first
    end
    if @post.nil?
      not_found
    end
  end

  def feed
    @posts = Monologue::Post.published
  end
end

app/controllers/monologue/tags_controller.rb
class Monologue::TagsController < Monologue::ApplicationController
  def show
    @tag = retrieve_tag
    if @tag
      @page = nil
      @posts = @tag.posts_with_tag
    else
      redirect_to :root ,notice: "No post found with label \"#{params[:tag]}\""
    end
  end

  private
  def retrieve_tag
    Monologue::Tag.where("lower(name) = ?", params[:tag].downcase).first
  end
end

app/helpers/monologue/application_helper.rb
module Monologue
  module ApplicationHelper
    include Monologue::Engine.routes.url_helpers if ENV["RAILS_ENV"] == "test" # TODO: try and see why this is needed for specs to pass
    #Why aren't they loaded by default?
    include Monologue::HtmlHelper
    include Monologue::TagsHelper

    def monologue_admin_form_for(object, options = {}, &block)
      options[:builder] = MonologueAdminFormBuilder
      form_for(object, options, &block)
    end

    def monologue_accurate_title
      content_for?(:title) ? ((content_for :title) + " | #{Monologue::Config.site_name}") : Monologue::Config.site_name
    end

    def rss_head_link
      tag("link", href: feed_url, rel: "alternate", title: "RSS", type: "application/rss+xml")
    end

    def rss_icon
      social_icon("rss", feed_url, Monologue::Config.show_rss_icon)
    end

    def github_icon
      social_icon("github", "http://github.com/#{Monologue::Config.github_username}", Monologue::Config.github_username)
    end

    def twitter_icon
      social_icon("twitter", "http://twitter.com/#{Monologue::Config.twitter_username}", Monologue::Config.twitter_username)
    end

    def linkedin_icon
      social_icon("linkedin", Monologue::Config.linkedin_url, Monologue::Config.linkedin_url)
    end

    def googleplus_icon
      social_icon("google-plus", Monologue::Config.google_plus_account_url, Monologue::Config.google_plus_account_url)
    end

    def facebook_icon
      social_icon("facebook", Monologue::Config.facebook_url, Monologue::Config.facebook_url)
    end

    def absolute_image_url(url)
      return url if url.starts_with? "http"
      request.protocol + request.host + url
    end

    def social_icon(foundicon, url, setting)
      return if setting.nil? || !setting
      content_tag :a, href: url, class: "social", target: "_blank" do
        content_tag :i, class: "foundicon-#{foundicon}" do # using an empty content tag for foundicons to appear. TODO: try to do otherwise and use only tag method
        end
      end
    end
  end
end

app/helpers/monologue/html_helper.rb
module Monologue
  module HtmlHelper


    # +li+ tag with the 'active' class added if the url is the current one.
    # Eg.:
    #
    #   <%= activable_li_tag users_path do  %>
    #     <%= link_to "Users", users_path %>
    #   <% end %>
    #
    def activable_li_tag(*url, &block)
      content_tag :li, capture(&block), :class => ("active" if url.any?{|u| current_page?(u)})
    end

    # +li+ tag with the 'active' class added if the url is the current one with a link
    # inside it pointing to that url.
    #
    #   <%= activatable_li_tag_with_link "Users", users_path %>
    #
    def activable_li_tag_with_link(title, *url)
      activable_li_tag *url do
        link_to(title, url.first)
      end
    end

    def sidebar_section_for(title, &block)
       content_tag(:section, class: 'widget') do
         content_tag(:header, content_tag(:h1, title)) +
             capture(&block)
       end
     end

  end
end

app/helpers/monologue/tags_helper.rb
module Monologue
  module TagsHelper

    #Number of sizes defined in the css
    NUMBER_OF_LABEL_SIZES = 5

    def tag_url(tag)
      "#{Monologue::Engine.routes.url_helpers.root_path}tags/#{tag.name.downcase}"
    end

    def label_for_tag(tag, min, max)
      "label-size-#{size_for_tag(tag, min, max)}"
    end

    def size_for_tag(tag, min, max)
      #logarithmic scaling based on the number of occurrences of each tag
      if min<max && tag.frequency>0
        1 + ((NUMBER_OF_LABEL_SIZES-1)*(log_distance_to_min(tag.frequency, min))/log_distance_to_min(max, min)).round
      else
        1
      end
    end

    private

    def log_distance_to_min(value, min)
      Math.log(value)-Math.log(min)
    end
  end
end

app/views/monologue/posts/404.html.erb
<% content_for :title do %>
  <%= t(".title") %>
<% end %>

<article>
  <header><h1><%= t(".title") %></h1></header>
  <p><%= t(".message") %></p>
</article>

app/views/monologue/posts/_pagination.html.erb
<div id="pagination">
  <% if @posts.total_pages > 1 && @posts.total_pages != @page.to_i %>
    <%= link_to t(".older_posts"), posts_page_path(@page.to_i+1), class: "older_posts" %>
  <% end %>

  <% if @posts.total_pages > 1 && @page.to_i > 1 %>
    <%= link_to t(".newer_posts"), posts_page_path(@page.to_i-1), class: "newer_posts" %>
  <% end %>
</div>

app/views/monologue/posts/_post.html.erb
<section>
  <%= render partial: 'monologue/posts/post_header', locals: {post: post} %>

  <div class="content" data-monologue="content">
    <%= truncate_html(post.content, length: 1000, omission: '...') %>
  </div>

  <div class="tags" data-monologue="tags">
    <%= render post.tags %>
  </div>
  <%= link_to t(".readmore"), post.full_url, class: "button" %>
</section>

app/views/monologue/posts/_post_header.html.erb
<header class="post-header">
  <h1><%= link_to post.title, post.full_url %></h1>
  <div class="posted">
    <span data-monologue="time">
      <time datetime="<%= post.published_at %>">
        <%= I18n.localize(post.published_at.to_date, format: :long) %>
      </time>
    </span>
    <span data-monologue="user">
      <%= post.user.name %>
    </span>
    <span data-monologue="disqus">
      <a href="<%= post.full_url + "#disqus_thread" %>"></a>
    </span>
  </div>
</header>

app/views/monologue/posts/_social_sharing.html.erb
<footer class="monologue-social-sharing" data-monologue="monologue-social-sharing">
  <span class="social-tagline"><%= t(".tagline") %></span>
  <div id="social-share">
    <div id="google-plus">
        <!-- GOOGLE +1 -->
         <!-- Placez cette balise là où vous souhaitez positionner le bouton +1. -->
         <g:plusone size="medium"></g:plusone>

         <!-- Placez cet appel d'affichage à l'endroit approprié. -->
         <script type="text/javascript">
           window.___gcfg = {lang: '<%=Monologue::Config.google_plusone_locale || "en" %>'};

           (function() {
             var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
             po.src = 'https://apis.google.com/js/plusone.js';
             var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
           })();
         </script>
        <!-- /GOOGLE +1 -->
       </div>
    <div id="twitter">
      <!-- TWITTER -->
      <a href="https://twitter.com/share" class="twitter-share-button"
          data-lang="<%= Monologue::Config.twitter_locale || "en" %>"
          data-url="<%= request.protocol %><%= request.host_with_port %><%= request.path.gsub("//","/") %>"
          data-via="<%=Monologue::Config.twitter_username%>"
          data-text="<%=@post.title%>"
          data-count="horizontal">Tweet</a>

      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      <!-- /TWITTER -->
    </div>


    <div id="facebook">
      <!-- FACEBOOK LIKE -->
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/<%= Monologue::Config.facebook_like_locale || "en_US" %>/all.js#xfbml=1&appId=288133081204194";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
      <div class="fb-like" data-send="false" data-width="450" data-show-faces="false"></div>
      <!-- /FACEBOOK LIKE -->
    </div>


  </div>
</footer>

app/views/monologue/posts/index.html.erb
<%= render @posts %>

<% if @page %>
	<%= render partial: "pagination" %>
<% end %>

app/views/monologue/posts/show.html.erb
<% content_for :title do %>
  <%= @post.title %>
<% end %>

<% content_for :meta_description do %>
  <%= strip_tags(@post.content) %>
<% end %>

<article>
  <%= render partial: 'monologue/posts/post_header', locals: {post: @post }%>
  <div class="content" data-monologue="content">
    <%= raw @post.content %>
  </div>

	<div class="tags" data-monologue="tags">
    <%= render @post.tags %>
  </div>

  <%= render "monologue/posts/social_sharing" %>

  <div id="disqus_thread"></div>
  <%= render 'layouts/monologue/application/disqus_embed' %>
  <noscript>Please enable JavaScript to view the comments.</noscript>
</article>